namespace Enviostisur.Models
{
    public class MDBalanza
    {
        public string ID_UNID { get; set; }
        public string ID_EMPR { get; set; }
        public string ID_EJES { get; set; }
        public string ST_CIER { get; set; }
        public string NU_MOVI_BDLO { get; set; }
        public string NU_MOVI { get; set; }
        public string ID_MOVI_BALA { get; set; }
        public string DE_TIPO { get; set; }
        public string ID_BALA { get; set; }
        public string TI_MOVI_INDI { get; set; }
        public string TI_MOVI { get; set; }
        public string ID_MOVI_DUES { get; set; }
        public string ID_MOVI_OPER { get; set; }
        public string FE_ENTR { get; set; }
        public string HO_ENTR { get; set; }
        public string FE_SALI { get; set; }
        public string HO_SALI { get; set; }
        public string ID_REGI_PLAC { get; set; }
        public string ID_TICK_ANTE { get; set; }
        public string NU_BREV { get; set; }
        public string NO_COND { get; set; }
        public string NU_DOCU_IDEN { get; set; }
        public string NO_TRAN { get; set; }
        public string ID_TRAN { get; set; }
        public string DE_NUME_TRAC { get; set; }
        public string DE_NUME_TAUX { get; set; }
        public string NU_EJES { get; set; }
        public string DE_CONF_VEHI { get; set; }
        public string CO_CLIE { get; set; }
        public string DE_CLIE { get; set; }
        public string NU_RECA { get; set; }
        public string NO_NAVE { get; set; }
        public string NU_SALI { get; set; }
        public string NO_DOCU { get; set; }
        public string TI_DOCU_ORIG { get; set; }
        public string NU_DOCU_ORIG { get; set; }
        public string ID_DOCU_ORIG { get; set; }
        public string NU_SECU_ITEM { get; set; }
        public string NU_CHAS { get; set; }
        public string ID_TIPO_JORN { get; set; }
        public string DE_TIPO_JORN { get; set; }
        public string ST_CERT_CESO { get; set; }
        public string NU_GUIA_REMI { get; set; }
        public string CO_BODE { get; set; }
        public string DE_BODE { get; set; }
        public string NU_FACT { get; set; }
        public string DE_CIUD { get; set; }
        public string ID_CIUD { get; set; }
        public string DE_CONT { get; set; }
        public string DE_OBSE { get; set; }
        public string FE_TRAN_BDLO { get; set; }
        public string HO_TRAN_BDLO { get; set; }
        public string ID_MOVI_BDLO { get; set; }
        public string PE_TARA { get; set; }
        public string CA_PES1 { get; set; }
        public string CA_PES2 { get; set; }
        public string DE_PERS_PES1 { get; set; }
        public string DE_PERS_PES2 { get; set; }
        public string ST_CIER_JORN { get; set; }
        public string DE_EDIT_PESO { get; set; }
        public string ST_CARG_CONT { get; set; }
        public string NO_USUA_CREA { get; set; }
        public string NO_USUA_MODI { get; set; } 
        public string FE_USUA_CREA { get; set; }
        public string FE_USUA_MODI { get; set; }
        public string DE_TIPO_SITU { get; set; }
        public string TI_SITU { get; set; }
        public string PE_RECE { get; set; }
        public string SA_DOCU_ORIG { get; set; }
        public string DE_PLAC { get; set; }
        public string ID_REGI_COND { get; set; }
        public string CA_PESO_SECO { get; set; }
        public string DE_MICS { get; set; }
        public string NU_PESO_MICS { get; set; }
        public string NU_CART_PORT { get; set; }
        public string NU_DUES { get; set; }
        public string NU_VUEL { get; set; }
        public string NU_TOTA_VUEL { get; set; }
        public string NU_NOTA_ENTR { get; set; }
        public string NU_MESA_PART { get; set; }
        public string NU_CORR_CONT { get; set; }
        public string CO_PERS_PES1 { get; set; }
        public string CO_PERS_PES2 { get; set; }
        public string CO_REGU_PESO { get; set; }
        public string CO_EDIT_PESO { get; set; }
        public string ST_EDIT_PESO { get; set; }
        public string DE_CLAS_CARG { get; set; }
        public string PC_HUME { get; set; }
        public string ST_INDI_CLAS { get; set; }
        public string DE_REGI { get; set; }
        public string CA_RECE { get; set; }
        public string CA_DESP { get; set; }
        public string DE_CARG { get; set; }
        public string DE_DIRE_WEBS { get; set; }
        public string DE_NOMB { get; set; }
        public string NU_RUCS { get; set; }
        public string ST_CARG_FRAC { get; set; }
        public string ST_CARG_GRAN { get; set; }
        public string ST_CARG_RODA { get; set; }
        public string ST_CONT_LLVA { get; set; }
        public string CA_TOTA { get; set; }
        public string ID_REGI { get; set; }
        public string DE_TIPO_EMBA { get; set; }
        public string ID_BAL2 { get; set; }
        public string NU_BULT { get; set; }
        public string NU_DOCU_DEST { get; set; }
        public string DE_DIRE { get; set; }
        public string ID_UBIG { get; set; }
        public string NU_DUAS { get; set; }
        public string DE_ZONA { get; set; }
        public string NU_DOCU_CLIE { get; set; }
        public string PR_ADUA_MANI { get; set; }
        public string NU_MANI { get; set; }

    }
}
